import { describe, expect, it } from 'vitest'
import {
  MAX_TABLES_PER_BATCH,
  MAX_TABLES_PER_STORE,
  isTableToken,
  nextTableNumber,
  parseTableNumbers,
  tableCheckoutPath,
  tableEntryPath,
  tableEntryUrl,
  tableOrderPath,
} from '@/lib/tables/qr'

const TOKEN = '0123456789abcdef01234567'

describe('table paths', () => {
  it('builds the public entry path', () => {
    expect(tableEntryPath('la-parrilla', TOKEN)).toBe(
      `/t/la-parrilla/mesa/${TOKEN}`,
    )
  })

  it('builds the checkout and order paths under the entry path', () => {
    expect(tableCheckoutPath('la-parrilla', TOKEN)).toBe(
      `/t/la-parrilla/mesa/${TOKEN}/checkout`,
    )
    expect(tableOrderPath('la-parrilla', TOKEN, 'abc')).toBe(
      `/t/la-parrilla/mesa/${TOKEN}/pedido/abc`,
    )
  })

  it('joins the base url without duplicating slashes', () => {
    expect(tableEntryUrl('https://tienda.app/', 'x', TOKEN)).toBe(
      `https://tienda.app/t/x/mesa/${TOKEN}`,
    )
    expect(tableEntryUrl('https://tienda.app', 'x', TOKEN)).toBe(
      `https://tienda.app/t/x/mesa/${TOKEN}`,
    )
  })
})

describe('isTableToken', () => {
  it('accepts the 24-hex tokens generated by the database default', () => {
    expect(isTableToken(TOKEN)).toBe(true)
  })

  it('rejects other shapes', () => {
    expect(isTableToken('')).toBe(false)
    expect(isTableToken('abc')).toBe(false)
    expect(isTableToken(`${TOKEN}0`)).toBe(false)
    expect(isTableToken('0123456789ABCDEF01234567')).toBe(false)
    expect(isTableToken('../t/other')).toBe(false)
  })
})

describe('nextTableNumber', () => {
  it('starts at 1 for an empty store', () => {
    expect(nextTableNumber([])).toBe(1)
  })

  it('continues after the highest existing number', () => {
    expect(nextTableNumber([1, 2, 5])).toBe(6)
  })

  it('ignores non-positive or non-integer values', () => {
    expect(nextTableNumber([-3, 0, 2.5])).toBe(1)
  })
})

describe('parseTableNumbers', () => {
  it('parses a single number', () => {
    expect(parseTableNumbers('4')).toEqual([4])
  })

  it('expands a range', () => {
    expect(parseTableNumbers('1-12')).toEqual(
      Array.from({ length: 12 }, (_, index) => index + 1),
    )
  })

  it('accepts comma separated lists and ranges, sorted and deduplicated', () => {
    expect(parseTableNumbers(' 5, 1-3 ,2 ')).toEqual([1, 2, 3, 5])
  })

  it('accepts a reversed range', () => {
    expect(parseTableNumbers('3-1')).toEqual([1, 2, 3])
  })

  it('returns an empty list for invalid input', () => {
    expect(parseTableNumbers('')).toEqual([])
    expect(parseTableNumbers('a-b')).toEqual([])
    expect(parseTableNumbers('0')).toEqual([])
    expect(parseTableNumbers('1-')).toEqual([])
    expect(parseTableNumbers('1--3')).toEqual([])
  })

  it('refuses ranges beyond the batch limit', () => {
    expect(parseTableNumbers('1-1000')).toEqual([])
  })
})

describe('table limits', () => {
  it('caps the dashboard listing above the bulk-creation batch size', () => {
    expect(MAX_TABLES_PER_STORE).toBe(500)
    expect(MAX_TABLES_PER_STORE).toBeGreaterThan(MAX_TABLES_PER_BATCH)
  })
})
