declare module '@tabler/icons-react' {
  import { SVGAttributes, ForwardRefExoticComponent, RefAttributes } from 'react'

  export interface TablerIconProps extends SVGAttributes<SVGSVGElement> {
    size?: number | string
    strokeWidth?: number | string
    absoluteStrokeWidth?: boolean
  }

  export type TablerIcon = ForwardRefExoticComponent<TablerIconProps & RefAttributes<SVGSVGElement>>

  // Export all icons as named exports
  export const Pizza: TablerIcon
  export const Hamburger: TablerIcon
  export const Steak: TablerIcon
  export const Salad: TablerIcon
  export const Coffee: TablerIcon
  export const FastFood: TablerIcon
  export const Sushi: TablerIcon
  export const IceCream: TablerIcon
  export const Donut: TablerIcon
  export const Bread: TablerIcon
  export const Cake: TablerIcon
  export const Taco: TablerIcon
  export const Burrito: TablerIcon
  export const BowlChopsticks: TablerIcon
  export const Sandwich: TablerIcon
  export const Chicken: TablerIcon
  export const Fish: TablerIcon
  export const Leaf: TablerIcon
  export const Sprout: TablerIcon
  export const WheatOff: TablerIcon
  export const Apple: TablerIcon
  export const Beer: TablerIcon
  export const Wine: TablerIcon
  export const Cocktail: TablerIcon
  export const Flame: TablerIcon
  export const Sparkles: TablerIcon
  export const Star: TablerIcon
  export const Award: TablerIcon
  export const Badge: TablerIcon
  export const Tag: TablerIcon
  export const Timer: TablerIcon
  export const HeartHandshake: TablerIcon
  export const Truck: TablerIcon
  export const MapPin: TablerIcon
  export const Clock: TablerIcon
  export const Star: TablerIcon
  export const Heart: TablerIcon
  export const User: TablerIcon
  export const Users: TablerIcon
  export const Lock: TablerIcon
  export const Unlock: TablerIcon
  export const Shield: TablerIcon
  export const Check: TablerIcon
  export const CheckCheck: TablerIcon
  export const X: TablerIcon
  export const ChevronDown: TablerIcon
  export const ChevronUp: TablerIcon
  export const ChevronLeft: TablerIcon
  export const ChevronRight: TablerIcon
  export const Menu: TablerIcon
  export const Close: TablerIcon
  export const Plus: TablerIcon
  export const Minus: TablerIcon
  export const Edit: TablerIcon
  export const Trash: TablerIcon
  export const Eye: TablerIcon
  export const EyeOff: TablerIcon
  export const Download: TablerIcon
  export const Upload: TablerIcon
  export const Share: TablerIcon
  export const Copy: TablerIcon
  export const Link: TablerIcon
  export const ExternalLink: TablerIcon
  export const Mail: TablerIcon
  export const Phone: TablerIcon
  export const MessageSquare: TablerIcon
  export const Bell: TablerIcon
  export const BellOff: TablerIcon
  export const Settings: TablerIcon
  export const Cog: TablerIcon
  export const Home: TablerIcon
  export const Store: TablerIcon
  export const Building: TablerIcon
  export const Receipt: TablerIcon
  export const CreditCard: TablerIcon
  export const Wallet: TablerIcon
  export const Coin: TablerIcon
  export const Percent: TablerIcon
  export const Gift: TablerIcon
  export const Zap: TablerIcon
  export const Bolt: TablerIcon
  export const Sun: TablerIcon
  export const Moon: TablerIcon
  export const Palette: TablerIcon
  export const Brush: TablerIcon
  export const Image: TablerIcon
  export const Camera: TablerIcon
  export const Video: TablerIcon
  export const Monitor: TablerIcon
  export const Laptop: TablerIcon
  export const Tablet: TablerIcon
  export const Phone: TablerIcon
  export const Watch: TablerIcon
  export const Headphones: TablerIcon
  export const Speaker: TablerIcon
  export const Microphone: TablerIcon
  export const Printer: TablerIcon
  export const Scanner: TablerIcon
  export const Projector: TablerIcon
  export const Tv: TablerIcon
  export const Radio: TablerIcon
  export const Gamepad: TablerIcon
  export const Joystick: TablerIcon
  export const Keyboard: TablerIcon
  export const Mouse: TablerIcon
  export const Stylus: TablerIcon
  export const Touchpad: TablerIcon
  export const Trackpad: TablerIcon
  export const Fingerprint: TablerIcon
  export const FaceId: TablerIcon
  export const Eye: TablerIcon
  export const EyeClosed: TablerIcon
  export const Scan: TablerIcon
  export const Qrcode: TablerIcon
  export const Barcode: TablerIcon
  export const Nfc: TablerIcon
  export const Bluetooth: TablerIcon
  export const Wifi: TablerIcon
  export const Signal: TablerIcon
  export const Battery: TablerIcon
  export const Charging: TablerIcon
  export const Plug: TablerIcon
  export const Outlet: TablerIcon
  export const Cable: TablerIcon
  export const Wireless: TablerIcon
  export const Sim: TablerIcon
  export const SdCard: TablerIcon
  export const Usb: TablerIcon
  export const Hdmi: TablerIcon
  export const Display: TablerIcon
  export const Monitor: TablerIcon
  export const Laptop: TablerIcon
  export const Tablet: TablerIcon
  export const Phone: TablerIcon
  export const Watch: TablerIcon
  export const Headphones: TablerIcon
  export const Speaker: TablerIcon
  export const Microphone: TablerIcon
  export const Camera: TablerIcon
  export const Video: TablerIcon
  export const Printer: TablerIcon
  export const Scanner: TablerIcon
  export const Projector: TablerIcon
  export const Tv: TablerIcon
  export const Radio: TablerIcon
  export const Gamepad: TablerIcon
  export const Joystick: TablerIcon
  export const Keyboard: TablerIcon
  export const Mouse: TablerIcon
  export const Stylus: TablerIcon
  export const Touchpad: TablerIcon
  export const Trackpad: TablerIcon
  export const Fingerprint: TablerIcon
  export const FaceId: TablerIcon
  export const Eye: TablerIcon
  export const EyeClosed: TablerIcon
  export const Scan: TablerIcon
  export const Qrcode: TablerIcon
  export const Barcode: TablerIcon
  export const Nfc: TablerIcon
  export const Bluetooth: TablerIcon
  export const Wifi: TablerIcon
  export const Signal: TablerIcon
  export const Battery: TablerIcon
  export const Charging: TablerIcon
  export const Plug: TablerIcon
  export const Outlet: TablerIcon
  export const Cable: TablerIcon
  export const Wireless: TablerIcon
  export const Sim: TablerIcon
  export const SdCard: TablerIcon
  export const Usb: TablerIcon
  export const Hdmi: TablerIcon

  // Catch-all for any other icons
  const icons: Record<string, TablerIcon>
  export default icons
}