import { expect, loginAs, test } from './fixtures'

// The seeded merchant (owner1) owns 'la-parrilla-del-norte'; its tables get a
// qr_token generated by the database default, so the URL is read from the
// dashboard instead of being hardcoded (see supabase/seed.sql around the
// store_tables insert).

test('an anonymous guest scans a table QR, orders with cash and reaches the tracking page', async ({
  page,
  browser,
}) => {
  await loginAs(page, 'merchant')
  await page.goto('/dashboard/tables')

  const firstTable = page.getByRole('article', { name: /^Mesa \d+$/ }).first()
  await expect(firstTable).toBeVisible()
  const tableUrl = await firstTable.locator('p[title]').getAttribute('title')
  if (!tableUrl) {
    throw new Error('Could not read the table QR target URL from /dashboard/tables.')
  }

  // Anonymous flow: a fresh, unauthenticated context simulates a diner
  // scanning the QR code with their own phone.
  const guestContext = await browser.newContext()
  try {
    const guestPage = await guestContext.newPage()
    await guestPage.goto(tableUrl)
    await expect(guestPage.getByRole('status')).toContainText('mesa')

    const productButtons = guestPage.getByRole('button', { name: /^Ver / })
    await expect(productButtons.first()).toBeVisible()
    await productButtons.first().click()

    const drawer = guestPage.getByRole('dialog')
    await expect(drawer).toBeVisible()
    const requiredGroups = drawer.locator('fieldset', { hasText: 'Obligatorio' })
    const requiredCount = await requiredGroups.count()
    for (let index = 0; index < requiredCount; index += 1) {
      await requiredGroups.nth(index).getByRole('radio').first().click()
    }
    // Bump the quantity so the order clears the store's minimum regardless
    // of which product happens to be first in the menu.
    const increment = drawer.getByRole('button', { name: 'Agregar uno' })
    for (let i = 0; i < 5; i += 1) {
      await increment.click()
    }
    await drawer.getByRole('button', { name: /^Agregar · / }).click()
    await expect(drawer).toBeHidden()

    await guestPage.getByRole('button', { name: /Abrir carrito/ }).click()
    const cart = guestPage.getByRole('dialog', { name: 'Tu pedido' })
    await expect(cart).toBeVisible()
    await cart.getByRole('link', { name: /Ir a pagar/ }).click()
    await guestPage.waitForURL('**/checkout')

    await guestPage.getByLabel('Tu nombre').fill('Invitado E2E')
    await guestPage.getByRole('radio', { name: /Pagar en la mesa/ }).click()
    await guestPage.getByRole('button', { name: 'Confirmar pedido' }).click()

    await guestPage.waitForURL(/\/pedido\/[0-9a-f-]{36}$/)
    await expect(guestPage.getByRole('heading', { level: 1 })).toBeVisible()
    await expect(guestPage.getByText(/^#/)).toBeVisible()
    await expect(guestPage.getByText('Pagar en la mesa')).toBeVisible()
  } finally {
    await guestContext.close()
  }
})
